"""Add reports relationship

Revision ID: 8925faa199d8
Revises: 13b15c589b23
Create Date: 2025-11-16 23:07:44.834193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8925faa199d8'
down_revision = '13b15c589b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('generated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('report_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('summary_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('pdf_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_unique_constraint('uq_report_uuid', ['uuid'])
        batch_op.create_foreign_key(None, 'users', ['generated_by'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_report_uuid', type_='unique')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('pdf_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('summary_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('report_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('generated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
